/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_2_group;

import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.InputMismatchException;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Hamza
 */
public class Payment_Screen extends javax.swing.JFrame {
    int cardID = 1234;
    int cvvNum = 1234;

    /**
     * Creates new form NewJFrame
     */
    public Payment_Screen() {
        initComponents();
        shop_adjustments();
        shop_Details();
        calculate_total();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        end_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cvv_enter = new javax.swing.JTextField();
        cardid_enter = new javax.swing.JTextField();
        payment_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        payment_table = new javax.swing.JTable();
        total_label = new javax.swing.JLabel();
        back_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Payment");

        end_button.setText("End");
        end_button.setToolTipText("");
        end_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                end_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(end_button)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(end_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("CardID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Cvv:");

        payment_button.setText("Finish Payment");
        payment_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payment_buttonActionPerformed(evt);
            }
        });

        payment_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(payment_table);

        total_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        total_label.setText("Total:");

        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cardid_enter)
                            .addComponent(cvv_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total_label)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(payment_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(back_button)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cardid_enter)
                    .addComponent(total_label))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(cvv_enter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payment_button)
                    .addComponent(back_button))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Handles the "Finish Payment" button action. It checks if the entered card ID and CVV match the predefined values and displays a message accordingly.
    private void payment_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payment_buttonActionPerformed
        
        try{
            int cardId_input = Integer.parseInt(cardid_enter.getText());
            int cvv_input = Integer.parseInt(cvv_enter.getText());
            if (cardId_input == cardID){
            if (cvv_input == cvvNum){
                JOptionPane.showMessageDialog(this, "Payment Successfull");
                end_program();
            } else{
                JOptionPane.showMessageDialog(this, "Incorrect cvv number");
            }
            }else{
            if (cvv_input == cvvNum){
                JOptionPane.showMessageDialog(this, "Incorrect cardID");
            }else{
                JOptionPane.showMessageDialog(this, "Incorrect cardID and cvv number");
            }
        }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Incorrect cardID and cvv number");
        }
  
        
        

    }//GEN-LAST:event_payment_buttonActionPerformed

    //Exits the program by calling the end_program() method.
    private void end_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_end_buttonActionPerformed
        end_program();
    }//GEN-LAST:event_end_buttonActionPerformed

    //Navigates back to the shopping cart screen.
    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        this.setVisible(false);
        new ShoppingCart_Screen().setVisible(true);
    }//GEN-LAST:event_back_buttonActionPerformed

    //Calculates the total price of items in the shopping cart and updates the total_label to display it.
    private void calculate_total(){
        String total_price_query = "SELECT SUM(price * quantity) AS total_price FROM shoppingcart";
        ResultSet total_price_set = MainProgram.shopping_cart.executeQuery(total_price_query);
        try{
            while(total_price_set.next()){
                double total_price = total_price_set.getDouble("total_price");
                String string_total = String.format("%.2f", total_price);
                total_label.setText("Total: $" + string_total);
            }
            
        }catch(SQLException e){
            e.printStackTrace();
            total_label.setText("Total: Error");
        }
    }
    
    public void shop_adjustments(){
        //Configures the payment_table (JTable) to display shopping details with specific column names.
        DefaultTableModel model_Product = new DefaultTableModel();
        // Populate the model with your data
        model_Product.addColumn("ID");
        model_Product.addColumn("Name");
        model_Product.addColumn("Price");
        model_Product.addColumn("Quantity");
        model_Product.addColumn("Category");
        
        
        TableColumnModel customcolumn = payment_table.getColumnModel();
        payment_table.setModel(model_Product);
        
        payment_table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        payment_table.getTableHeader().setReorderingAllowed(false);
        
        customcolumn.getColumn(0).setResizable(false);
        customcolumn.getColumn(0).setPreferredWidth(600);
        
        customcolumn.getColumn(1).setResizable(false);
        customcolumn.getColumn(1).setPreferredWidth(600);

        customcolumn.getColumn(2).setResizable(false);
        customcolumn.getColumn(2).setPreferredWidth(600);
        
        customcolumn.getColumn(3).setResizable(false);
        customcolumn.getColumn(3).setPreferredWidth(600);
        
        customcolumn.getColumn(4).setResizable(false);
        customcolumn.getColumn(4).setPreferredWidth(600);
    }
    
    //Configures the payment_table (JTable) to display shopping details with specific column names.
    public void shop_Details(){
        DefaultTableModel model = (DefaultTableModel) payment_table.getModel();
        model.setRowCount(0);
        
        ResultSet item_Result = MainProgram.shopping_cart.executeQuery("SELECT * FROM shoppingcart");
   
        try{
            while (item_Result.next()){
                int id = item_Result.getInt("id");
                String name = item_Result.getString("name");
                double price = item_Result.getDouble("price");
                int quantity = item_Result.getInt("quantity");
                String category = item_Result.getString("category");
                
                model.addRow(new Object[]{id,name,price,quantity,category});
            }
            
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    
    //Closes database connections and exits the application.
    public void end_program(){
        MainProgram.signup_list.closeConnection();
        MainProgram.shopping_cart.closeConnection();
        MainProgram.shop_items.closeConnection();
        System.exit(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment_Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JTextField cardid_enter;
    private javax.swing.JTextField cvv_enter;
    private javax.swing.JButton end_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton payment_button;
    private javax.swing.JTable payment_table;
    private javax.swing.JLabel total_label;
    // End of variables declaration//GEN-END:variables
}
